apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m
  path: "./nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: clusters
    namespace: flux-system